title: My AWS Journey
description: Documenting my learning path through AWS as a Node.js Engineer.
baseurl: "" # Leave empty unless it's a subpath
url: "https://varshinips.github.io/Varshini/"
theme: minima
